server :
  port: 8888
spring:
  liquibase:
    change-log: classpath:migrations/changelog.yml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: ru.relex.db.handler
